// Glowtone 12-type palette dataset (Korean personal color / 퍼스널 컬러 naming).
// Axes for prototypes: t = temperature (+warm / -cool), v = value (+light / -deep), c = chroma (+clear / -mute).
// Colors are hand-picked to match each type's hue (warm = yellow-based, cool = blue-based),
// value (lightness) and chroma (clarity) ranges, following common Korean & seasonal color references.
export const TYPES = [
{ id:"spring-light", season:"Spring", tone:"Warm", sub:"Light", ko:"봄 웜 라이트", proto:[0.55,0.8,0.15],
  traits:"Light · warm · fresh, slightly soft · low–medium contrast",
  desc:"Sunny and airy. Light, warm, gently clear colors make your skin look bright and dewy.",
  card:["#FFF1DE","#F9D9BE"],
  best:[["Peach","#FFC9A3"],["Apricot","#FBB98A"],["Light coral","#F4A285"],["Butter yellow","#F7E08F"],["Mint","#BDE5C8"],["Light warm aqua","#9FD9CC"],["Warm periwinkle","#A9C2EA"],["Salmon pink","#F6A79A"],["Ivory","#FFF6E0"],["Light camel","#D9B48F"]],
  worst:[["Black","#141414"],["Burgundy","#6D1A36"],["Charcoal","#3C3C3C"],["Fuchsia","#C0157A"],["Dark navy","#1B2440"],["Olive drab","#5F5A33"]],
  neutrals:[["Ivory","#FFF6E0"],["Cream","#F6EAD2"],["Light beige","#E8D3B5"],["Light camel","#D9B48F"],["Warm light gray","#CFC6BA"]],
  makeup:{lip:[["Peach","#F5A487"],["Coral pink","#F2887F"],["Light salmon","#EF9A86"]],blush:[["Apricot","#F7B48E"],["Peach","#FAC0A2"]],eyes:[["Champagne","#EED9B6"],["Peach","#F3BE9C"],["Light brown","#B98E68"]]},
  hair:[["Honey brown","#A97446"],["Milk-tea brown","#B48A68"],["Light golden brown","#9B6A3E"]],
  metals:["Light yellow gold","Rose gold"], tip:"Keep outfits light and low-contrast; swap black for soft beige or light camel." },
{ id:"spring-bright", season:"Spring", tone:"Warm", sub:"Bright", ko:"봄 웜 브라이트", proto:[0.55,0.3,0.65],
  traits:"Warm · clear & bright · medium value · medium–high contrast",
  desc:"Lively and sparkling. Clear, warm, juicy colors make your eyes and skin pop.",
  card:["#FFE9D2","#FFC9A8"],
  best:[["Coral","#FF7F61"],["Warm red","#EE4B2B"],["Tangerine","#FF9A3C"],["Golden yellow","#FFC72C"],["Apple green","#5DBB46"],["Turquoise","#2EC4B6"],["Clear warm blue","#3F8FD8"],["Coral pink","#FF8C94"],["Warm ivory","#FFF3D6"],["Golden camel","#C8955A"]],
  worst:[["Dusty mauve","#B08E9A"],["Ash gray","#9A9A9A"],["Charcoal","#3C3C3C"],["Burgundy","#6D1A36"],["Grayish olive","#7A7A5C"],["Black","#141414"]],
  neutrals:[["Warm ivory","#FFF3D6"],["Golden camel","#C8955A"],["Warm navy","#2C3E6B"],["Cream","#F6EAD2"],["Milk chocolate","#7B4B2A"]],
  makeup:{lip:[["Coral","#FF6F59"],["Warm red","#E5432F"],["Juicy orange-pink","#FF7F6E"]],blush:[["Coral","#FF8B70"],["Warm pink","#F7928A"]],eyes:[["Gold shimmer","#E2B65A"],["Warm brown","#9A6234"],["Coral","#F28A6B"]]},
  hair:[["Golden brown","#94602F"],["Copper brown","#9A4E2A"],["Bright chestnut","#7E4521"]],
  metals:["Shiny yellow gold"], tip:"Pair one clear warm color with ivory for a fresh, high-energy look." },
{ id:"spring-vivid", season:"Spring", tone:"Warm", sub:"Vivid", ko:"봄 웜 비비드", proto:[0.65,0.0,0.95],
  traits:"Warm · most saturated · medium value · high contrast",
  desc:"Bold and radiant. Fully saturated warm colors that would overwhelm others look natural on you.",
  card:["#FFE2C4","#FFB38A"],
  best:[["Tomato red","#E8361D"],["Vivid orange","#FF7A00"],["Sunflower","#FFB800"],["Vivid green","#2BB24C"],["Bright turquoise","#00A6A6"],["Hot coral","#FF5A4E"],["Clear blue","#2F6FDE"],["Warm magenta-pink","#F0437A"],["Ivory","#FFF6E0"],["Golden brown","#9A6A2E"]],
  worst:[["Dusty rose","#C9A0A8"],["Gray-beige","#B9AFA4"],["Mauve","#B58A9E"],["Charcoal","#3C3C3C"],["Muted khaki","#A89F7B"],["Icy pastels","#E3EAF4"]],
  neutrals:[["Ivory","#FFF6E0"],["Camel","#C19A6B"],["Golden brown","#9A6A2E"],["Warm navy","#2C3E6B"],["Bright white-cream","#FFF9EC"]],
  makeup:{lip:[["Tomato red","#E23B26"],["Hot coral","#FF5A4E"],["Orange red","#F04E23"]],blush:[["Bright coral","#FF7A5C"],["Orange-pink","#FF8A66"]],eyes:[["Bronze-gold","#C9922E"],["Orange brown","#B5652A"],["Teal liner","#00838A"]]},
  hair:[["Bright golden brown","#9C5E25"],["Orange brown","#A0522D"],["Rich chestnut","#6F3B1D"]],
  metals:["Polished yellow gold"], tip:"Go for color-blocking and saturated prints; avoid grayed or dusty shades." },
{ id:"summer-light", season:"Summer", tone:"Cool", sub:"Light", ko:"여름 쿨 라이트", proto:[-0.55,0.8,0.05],
  traits:"Cool · light · soft-clear pastels · low contrast",
  desc:"Fresh and gentle. Cool pastels make your skin look clear and rosy.",
  card:["#EEF2FB","#D9D3F0"],
  best:[["Powder blue","#B7D3EE"],["Lavender","#C9B8E8"],["Baby pink","#F6C1D1"],["Light rose","#EBA9BE"],["Cool mint","#B5E3D8"],["Periwinkle","#A5B4E8"],["Sky blue","#9CC7E8"],["Lilac","#D7BDE2"],["Soft white","#F7F7F5"],["Light cool gray","#D3D6DC"]],
  worst:[["Orange","#F28C28"],["Mustard","#C9A227"],["Camel","#C19A6B"],["Olive","#6B6B2A"],["Rust","#B7410E"],["Black","#141414"]],
  neutrals:[["Soft white","#F7F7F5"],["Light cool gray","#D3D6DC"],["Gray-blue","#9AAEC4"],["Rose beige","#E3CFCB"],["Soft navy","#3E4C6E"]],
  makeup:{lip:[["Baby pink","#F2A7BC"],["Rose pink","#E68AA6"],["Strawberry milk","#F4B3C2"]],blush:[["Light rose","#F2B3C4"],["Lavender pink","#E9B8D6"]],eyes:[["Pink-beige","#E6C3C3"],["Lavender","#C9B8E8"],["Cool taupe","#A3958F"]]},
  hair:[["Ash brown","#7A6A5E"],["Rosy brown","#8B6B66"],["Soft cool brown","#6E5A50"]],
  metals:["Silver","White gold","Light rose gold"], tip:"Stay light and airy; pick soft white over stark white and gray-navy over black." },
{ id:"summer-bright", season:"Summer", tone:"Cool", sub:"Bright", ko:"여름 쿨 브라이트", proto:[-0.5,0.35,0.55],
  traits:"Cool · clear · light–medium value · medium contrast",
  desc:"Bright and refreshing. Clear, cool colors with a little sparkle wake up your face.",
  card:["#EAF1FB","#F3CFE0"],
  best:[["Clear rose pink","#F06292"],["Watermelon pink","#F2547D"],["Cool aqua","#4FC3D9"],["Cornflower","#6495ED"],["Bright lavender","#9C7FE0"],["Cool mint","#6FD6C1"],["Raspberry","#D63C72"],["Bright sky","#5AB4F0"],["Pure soft white","#FAFAFA"],["Cool navy","#24375F"]],
  worst:[["Orange","#F28C28"],["Mustard","#C9A227"],["Khaki","#A89F7B"],["Camel","#C19A6B"],["Rust","#B7410E"],["Dull olive","#6B6B4B"]],
  neutrals:[["Soft white","#FAFAFA"],["Cool gray","#B8BDC7"],["Cool navy","#24375F"],["Gray-blue","#8DA3B8"],["Rose taupe","#A48A90"]],
  makeup:{lip:[["Clear rose","#E9547F"],["Raspberry","#D63C72"],["Cool watermelon","#F06A8A"]],blush:[["Cool pink","#F28AAE"],["Fresh rose","#EE7FA0"]],eyes:[["Silver-pink shimmer","#E8C9D6"],["Plum","#7E4A73"],["Cool brown","#7A625C"]]},
  hair:[["Cool dark brown","#4E3B33"],["Ash brown","#6E5B50"],["Soft black","#2A2526"]],
  metals:["Silver","White gold","Platinum"], tip:"Clear cool brights near your face; balance with soft white or gray-blue." },
{ id:"summer-mute", season:"Summer", tone:"Cool", sub:"Mute", ko:"여름 쿨 뮤트", proto:[-0.5,0.2,-0.7],
  traits:"Cool · soft & grayed · medium value · low contrast",
  desc:"Elegant and calm. Soft, grayed cool tones blend beautifully with your skin.",
  card:["#ECEAF0","#D6CCD8"],
  best:[["Dusty rose","#C9A0A8"],["Mauve","#B58A9E"],["Gray-blue","#8DA3B8"],["Slate blue","#6F84A3"],["Lavender gray","#A9A1BE"],["Sage gray","#9DB0A3"],["Rose brown","#A57F84"],["Soft navy","#4F5D75"],["Cool cocoa","#8C7A78"],["Soft white","#F2F1EE"]],
  worst:[["Bright orange","#FF7A00"],["Pure black","#000000"],["Neon green","#39FF14"],["Mustard","#C9A227"],["Tomato red","#E8361D"],["Bright gold-yellow","#FFC72C"]],
  neutrals:[["Soft white","#F2F1EE"],["Gray-beige","#BDB5AD"],["Cool taupe","#8F8483"],["Soft navy","#4F5D75"],["Medium cool gray","#8E939B"]],
  makeup:{lip:[["Dusty rose","#C47F8E"],["Mauve pink","#B9768C"],["MLBB rose","#B87A80"]],blush:[["Dusty pink","#D6A1AD"],["Soft mauve","#C99AAE"]],eyes:[["Taupe","#9A8C86"],["Mauve","#A88596"],["Gray-brown","#7C716C"]]},
  hair:[["Ash brown","#6E5F57"],["Cool mocha","#5E4D47"],["Greige brown","#7F7068"]],
  metals:["Matte silver","White gold","Pewter"], tip:"Tone-on-tone outfits in soft cool shades look polished; skip high contrast." },
{ id:"autumn-mute", season:"Autumn", tone:"Warm", sub:"Mute", ko:"가을 웜 뮤트", proto:[0.55,0.1,-0.7],
  traits:"Warm · soft & earthy · medium value · low contrast",
  desc:"Soft, earthy and cozy. Muted warm colors with golden warmth bring out your natural glow.",
  card:["#F3E6D3","#D8BFA5"],
  best:[["Camel","#C19A6B"],["Dusty rose brown","#A8756A"],["Olive","#8A8B5C"],["Muted mustard","#C9A55C"],["Muted teal","#5E7F7A"],["Warm taupe","#9C8572"],["Soft terracotta","#B9876A"],["Moss","#6F7553"],["Khaki beige","#C8B79A"],["Salmon beige","#D4A58D"]],
  worst:[["Neon pink","#FF3EA5"],["Icy blue","#DDEBF7"],["Pure white","#FFFFFF"],["Black","#141414"],["Fuchsia","#C0157A"],["Cobalt","#0047AB"]],
  neutrals:[["Oatmeal","#E3D5BE"],["Camel","#C19A6B"],["Warm taupe","#9C8572"],["Cocoa brown","#6E5240"],["Khaki","#B5A67E"]],
  makeup:{lip:[["Rose brown","#A8675E"],["Brick rose","#B06A5A"],["Nude coral","#C58A73"]],blush:[["Soft terracotta","#C98C75"],["Peach beige","#D9A68C"]],eyes:[["Khaki","#8F8660"],["Warm taupe","#9C8572"],["Soft bronze","#A7814F"]]},
  hair:[["Soft brown","#6F5241"],["Olive brown","#5E4C36"],["Warm mocha","#6B4D3A"]],
  metals:["Matte gold","Brushed brass","Bronze"], tip:"Layer earthy neutrals with one muted accent; ivory/oatmeal beats stark white." },
{ id:"autumn-strong", season:"Autumn", tone:"Warm", sub:"Strong", ko:"가을 웜 스트롱", proto:[0.65,-0.3,0.3],
  traits:"Warm · rich & saturated · medium–deep value · medium–high contrast",
  desc:"Rich and confident. Saturated, spicy warm colors match your intensity.",
  card:["#F3DFC6","#D9A77E"],
  best:[["Rust","#B7410E"],["Burnt orange","#CC5500"],["Mustard","#D4A017"],["Brick red","#B23A2A"],["Warm forest green","#3D6B3A"],["Petrol teal","#1F6F78"],["Golden brown","#996515"],["Olive","#6B6B2A"],["Camel","#C19A6B"],["Cream","#F3E5C8"]],
  worst:[["Baby pink","#F6C1D1"],["Icy lavender","#E3DDF2"],["Fuchsia","#C0157A"],["Cool gray","#A3A8B0"],["Silver gray","#C0C0C0"],["Powder blue","#B7D3EE"]],
  neutrals:[["Cream","#F3E5C8"],["Camel","#C19A6B"],["Chocolate","#5A3A22"],["Olive","#6B6B2A"],["Warm charcoal-brown","#4A3F35"]],
  makeup:{lip:[["Brick red","#A8392B"],["Burnt orange","#C0532E"],["Terracotta","#B5573C"]],blush:[["Terracotta","#C26A4E"],["Warm bronze","#B9784F"]],eyes:[["Copper","#B0602E"],["Bronze","#8C6A2F"],["Olive","#6B6B2A"]]},
  hair:[["Chestnut","#6B3A1F"],["Copper brown","#8A4626"],["Dark golden brown","#5C3A1E"]],
  metals:["Yellow gold","Copper","Antique brass"], tip:"Rich warm colors and textured fabrics (suede, knit) suit you; avoid icy pastels." },
{ id:"autumn-deep", season:"Autumn", tone:"Warm", sub:"Deep", ko:"가을 웜 딥", proto:[0.55,-0.8,-0.15],
  traits:"Warm · deep & rich · dark value · medium–high contrast",
  desc:"Deep and luxe. Dark, warm, rich colors look natural and grounded on you.",
  card:["#EBD9C4","#B98E6E"],
  best:[["Dark chocolate","#4E2A1E"],["Warm burgundy","#7B2D26"],["Deep olive","#4B5320"],["Dark teal","#1D4E4C"],["Deep pumpkin","#B04A14"],["Bronze","#8C6A2F"],["Forest green","#2E4A2E"],["Deep mustard","#A67C00"],["Espresso","#3B2A20"],["Warm cream","#EFE0C4"]],
  worst:[["Pastel pink","#F6C1D1"],["Icy blue","#DDEBF7"],["Light gray","#D3D6DC"],["Lilac","#D7BDE2"],["Neon yellow","#E6FF3E"],["Cool fuchsia","#C0157A"]],
  neutrals:[["Espresso","#3B2A20"],["Dark chocolate","#4E2A1E"],["Deep olive","#4B5320"],["Warm cream","#EFE0C4"],["Dark camel","#9A7048"]],
  makeup:{lip:[["Brick brown","#8A3A2C"],["Warm burgundy","#7B2D26"],["Deep terracotta","#9C4A35"]],blush:[["Deep peach-brown","#B26E52"],["Bronze","#A0683F"]],eyes:[["Deep bronze","#7A5426"],["Chocolate","#4E2A1E"],["Dark olive","#4B5320"]]},
  hair:[["Dark chocolate brown","#3E2A1F"],["Deep auburn","#5A2A1A"],["Warm espresso","#33231A"]],
  metals:["Antique gold","Bronze","Copper"], tip:"Deep warm neutrals (espresso, olive) replace black beautifully." },
{ id:"winter-bright", season:"Winter", tone:"Cool", sub:"Bright", ko:"겨울 쿨 브라이트", proto:[-0.55,0.05,0.8],
  traits:"Cool · clear & icy-bright · medium value · high contrast",
  desc:"Crisp and striking. Clear cool colors and icy accents match your high contrast.",
  card:["#EEF1FA","#C9D2F2"],
  best:[["True red","#D0103A"],["Fuchsia","#E0218A"],["Cobalt","#0047AB"],["Emerald","#009B77"],["Cool turquoise","#00B5C9"],["Royal purple","#6A2BA0"],["Icy pink","#F7D8E6"],["Icy lemon","#F4F7A8"],["Pure white","#FFFFFF"],["Black","#141414"]],
  worst:[["Camel","#C19A6B"],["Orange","#F28C28"],["Mustard","#C9A227"],["Olive","#6B6B2A"],["Rust","#B7410E"],["Dusty beige","#C8B79A"]],
  neutrals:[["Pure white","#FFFFFF"],["Black","#141414"],["Charcoal","#36393F"],["Navy","#1B2A4A"],["Icy gray","#E4E7EC"]],
  makeup:{lip:[["Blue-red","#C8102E"],["Fuchsia","#D6247F"],["Cool berry","#B0245C"]],blush:[["Cool pink","#F07AA6"],["Fuchsia tint","#E36A9E"]],eyes:[["Silver shimmer","#D9DCE3"],["Plum","#6B2E5F"],["Black liner","#141414"]]},
  hair:[["Blue-black","#121318"],["Cool dark brown","#2E2522"],["Soft black","#1E1B1C"]],
  metals:["Silver","Platinum","White gold"], tip:"High contrast is your friend: black + white, or one jewel color with white." },
{ id:"winter-vivid", season:"Winter", tone:"Cool", sub:"Vivid", ko:"겨울 쿨 비비드", proto:[-0.6,-0.3,0.95],
  traits:"Cool · most saturated · medium–deep value · very high contrast",
  desc:"Bold and dramatic. Pure, vivid cool colors look effortless on you.",
  card:["#ECEBF8","#C3B6EC"],
  best:[["Magenta","#D1007A"],["True red","#C8102E"],["Royal blue","#2547D0"],["Emerald","#00845A"],["Violet","#7B2FBE"],["Hot pink","#FF1F8E"],["Electric teal","#00A3AD"],["Lemon","#F5E663"],["Pure white","#FFFFFF"],["Black","#141414"]],
  worst:[["Beige","#D8C7A8"],["Camel","#C19A6B"],["Dusty rose","#C9A0A8"],["Khaki","#A89F7B"],["Rust","#B7410E"],["Peach","#FFC9A3"]],
  neutrals:[["Black","#141414"],["Pure white","#FFFFFF"],["Navy","#1B2A4A"],["Charcoal","#36393F"],["Cool gray","#9EA3AB"]],
  makeup:{lip:[["Magenta","#C2006F"],["True red","#C8102E"],["Vivid fuchsia","#E0218A"]],blush:[["Bright cool pink","#F0609A"],["Berry","#C23A72"]],eyes:[["Black liner","#141414"],["Royal blue","#2547D0"],["Deep plum","#4B1E4F"]]},
  hair:[["Jet black","#0E0E10"],["Blue-black","#121318"],["Cool espresso","#241C1A"]],
  metals:["Bright silver","Platinum"], tip:"Saturated color-blocking with black or white; skip muted and earthy tones." },
{ id:"winter-deep", season:"Winter", tone:"Cool", sub:"Deep", ko:"겨울 쿨 딥", proto:[-0.55,-0.8,0.2],
  traits:"Cool · deep & dark · dark value · high contrast",
  desc:"Deep and sophisticated. Dark cool colors give you a chic, intense look.",
  card:["#E6E6EE","#9E9CB8"],
  best:[["Black","#141414"],["Deep navy","#1B2A4A"],["Cool burgundy","#6D1A36"],["Deep plum","#4B1E4F"],["Pine green","#0B5345"],["Cool ruby","#9B111E"],["Ink blue","#233A6E"],["Charcoal","#333638"],["Pure white","#FFFFFF"],["Silver gray","#C0C3C8"]],
  worst:[["Camel","#C19A6B"],["Orange","#F28C28"],["Peach","#FFC9A3"],["Mustard","#C9A227"],["Warm beige","#D8C3A0"],["Light coral","#F4A285"]],
  neutrals:[["Black","#141414"],["Charcoal","#333638"],["Deep navy","#1B2A4A"],["Pure white","#FFFFFF"],["Silver gray","#C0C3C8"]],
  makeup:{lip:[["Deep berry","#7E1F45"],["Cool burgundy","#6D1A36"],["Ruby red","#9B111E"]],blush:[["Cool rose","#C2607E"],["Berry","#A0405E"]],eyes:[["Charcoal","#333638"],["Plum","#4B1E4F"],["Navy liner","#1B2A4A"]]},
  hair:[["Black","#141414"],["Cool dark brown","#2B2220"],["Deep burgundy-black","#2A1419"]],
  metals:["Silver","White gold","Gunmetal"], tip:"Dark cool neutrals with crisp white are your power combo." }
];
export const byId = Object.fromEntries(TYPES.map(t => [t.id, t]));
export const nameOf = t => `${t.season} ${t.tone} ${t.sub}`;
